name: Build

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch: # allows to be run manually
  workflow_call: # when called from another workflow

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Build site
        run: |
          mkdir -p _site
          find . -maxdepth 1 -mindepth 1 -not -name _site -not -name '*.md' -not -name LICENSE -not -name .github -not -name .gitignore -not -name .git -exec cp -r '{}' _site \;
      - name: Save built site for deploy
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site
          retention-days: 7
